### ISSUE TITLE
[Future] Ubuntu/Debian Server 16.04 LTS Configuration

### ISSUE THREAD

**Issue by g7morris** [islandora-interest-groups/Islandora-DevOps-Interest-Group#10]
For those assigned to this issue by mention or Assignee: 

Please update this section https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/wiki/Software-Requirements-by-Distro  with the appropriate information for [Future] Ubuntu/Debian Server 16.04 LTS Configuration

Attaching spreadsheets are fine. Please let me know if I've left anyone out or if you don't want this distro.

Assigned to: 
@bradspry
@pc37utn
@philred
@lo5an
@JacobSanford
@jpeak5
@mark-cooper
@lutaylor
@JacobSanford
@bradspry
@psuda1

**Comment by lo5an** [comment]
It's good to have this on our TODO list, but Ubuntu 16.04 will come out in April of 2016, so it will be a back burner issue for awhile. By then, I expect that we'll have solid 14.04 docs that we can update for whatever changes are required by 16.04.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
