### ISSUE TITLE
Best Practices Page

### ISSUE THREAD

**Issue by g7morris** [islandora-interest-groups/Islandora-DevOps-Interest-Group#11]
For those assigned to this issue by mention or Assignee: 

Please update this section Best Practices
https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/wiki/Best-Practices

Please let me know if I've left anyone out or if you don't want this distro.

Assigned to: 
@bradspry
@pc37utn
@philred
@lo5an
@JacobSanford
@jpeak5
@mark-cooper
@lutaylor
@JacobSanford
@bradspry
@psuda1

**Comment by pc37utn** [comment]
Hi,
     Does this group have a google-group or a google doc?  I am getting 
the github notices but not sure what they are talking about.

   I finally found an email from Aug 4 that mentions the next meeting 
being the 12th, (today!) but I have no other info.

```
Is there a general instructions for this interest group?
```

I am getting email from several other groups but none from this one.

Paul

**Comment by mjordan** [comment]
@pc37utn Send me a skype request (mark.jordan50) and I'll bring you into the Sept. 8 call. We don't have a Google group. More info is available at https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
