### ISSUE TITLE
Updates to Ubuntu 14.04 doumentation

### ISSUE THREAD

**Issue by lutaylor** [islandora-interest-groups/Islandora-DevOps-Interest-Group#16]
Providing a pull to fix the following issues

---Updating documentation---

Adding known good commit for libvpx to address ffmpeg build issues mentioned here:

https://groups.google.com/forum/#!topic/islandora/xCqSqeD1wZU

FFmpeg 1.1.1 build will fail if using libvpx from head

It is more secure to have openoffice start with its own user account vs using apache user. Updating documentation to reflect more secure method. 

Noted issues with openseadragon-bin-1.1.1. The clipper doesn't work right. Sticking with recommended version openseadragon-bin-0.9.129.zip as per README https://github.com/Islandora/islandora_openseadragon

Adding some notes about securing drupal file system permissions on systems exposed to internet. This is to address concerns raised in https://www.drupal.org/PSA-2015-001 and to be complaint with https://www.drupal.org/node/244924

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
