### ISSUE TITLE
Clean up markup in ubuntu guide

### ISSUE THREAD

**Issue by lutaylor** [islandora-interest-groups/Islandora-DevOps-Interest-Group#18]
I am not very good with the mark up in the readme. If anyone is skilled at this could they clean it up and make it look pretty?

**Comment by manez** [comment]
Not super-skilled, but have worked with it enough to give it a go. Should I wait for #17 to go in?

**Comment by lutaylor** [comment]
As long as you don't tweak the mark up around the sections in the pull it should be ok. Even if you do edit those sections it is is only a few small changes that can easily be put in again.

**Comment by lutaylor** [comment]
Thanks for the help Melissa. It could look a lot nicer :)

**Comment by lutaylor** [comment]
Mark up looks good this issue should be good to close.
