### ISSUE TITLE
Expanding to broader community

### ISSUE THREAD

**Issue by awoods** [islandora-interest-groups/Islandora-DevOps-Interest-Group#20]
I notice that there is also a devops interest group in the Hydra community:
https://wiki.duraspace.org/display/hydra/Hydra+DevOps+Interest+Group

Are the devops needs different enough between Islandora and Hydra that these two groups could not conceivably be one?

**Comment by DonRichards** [comment]
I'm not sure. Sorry it took so long to respond. Some of their charter would be relevant 
* Continuous integration and testing
* Performance testing, profiling, scaling, and high availability
* Application usage reporting, monitoring, and alerting
* Security management, auditing, backups, and disaster recovery
* Virtualization and containerization (e.g. Docker, Vagrant)

But stuff like project and server environments and architecture would differ greatly.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
