### ISSUE TITLE
Leftover To Dos from Deployment guide

### ISSUE THREAD

**Issue by manez** [islandora-interest-groups/Islandora-DevOps-Interest-Group#22]
A brief list of tasks to follow up on, removed from the deployment guide when it was formatted for #18 :
- SSH keys
- User accounts e.g. islandora
- Sudoers config (location, ideal setup) 
- iptables (turn off for initial deploy?) 
- Install Dependencies and Pre-setup

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
