### ISSUE TITLE
Update Fits version in deployment guide to 1.0.1

### ISSUE THREAD

**Issue by lutaylor** [islandora-interest-groups/Islandora-DevOps-Interest-Group#30]
see discussion here:

https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/pull/29#issuecomment-245363293

Referencing old version should be fairly safe to put in PR to upgrade to 1.0.1 or perhaps the same version that gets installed with the islandora_vagrant box.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
