### ISSUE TITLE
Installation script/playbook

### ISSUE THREAD

**Issue by Natkeeran** [islandora-interest-groups/Islandora-DevOps-Interest-Group#32]
[Provisioning-Islandora-on-Ubuntu](https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/blob/master/Deployment%20Guides/Provisioning-Islandora-on-Ubuntu.md) document states that "within this repository, there will be a stand alone bash script designed to install an all-in-one Islandora stack upon any type of platform e.g Virtual Machine, bare metal server etc.".  Is there any update on this work?  Is there a recommended ansible playbook for islandora full stack instillation?

**Comment by egesu** [comment]
Hey @Natkeeran, I've tried to do some stuff [here](https://github.com/egesu/islandora-ubuntu-setup). However I've done it for my deployment and I need to use remote Solr and Adore Djatoka. But you can read and run the scripts. I would not be very difficult. By the way I've generated these scripts using the link you shared.

**Comment by edf** [comment]
@Natkeeran  Have you seen https://github.com/jefferyb/islandora-7.x-enterprise-ansible ?

**Comment by Natkeeran** [comment]
@egesu @edf Thank you for the links and info.  I will try these out.

**Comment by lutaylor** [comment]
@Natkeeran 

I have an outstanding pull https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/pull/24 that has been opened since June if someone wants to merge... additional updates will be forth coming once the pull is in place. It is not quite a stand alone batch script but can be easily made into one.

**Comment by Natkeeran** [comment]
I was able to install the full stack using the  https://github.com/jefferyb/islandora-7.x-enterprise-ansible.  I did encounter some issues, which I have reported there.  Will be looking at shell scripts to install other components.  Thank you all for the responses.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
