### ISSUE TITLE
First time trying this... Provisioning-Islandora-on-Ubuntu.md

### ISSUE THREAD

**Issue by bdgregg** [islandora-interest-groups/Islandora-DevOps-Interest-Group#36]
Just went through this script to build an Islandora system and only found a couple things that threw me off.  These aren't big, but I wanted to provide some feedback.  

One is a step before the "service tomcat deploy" line where I found that /usr/share/tomcat wasn't symlinked over to /usr/local/fedora/tomcat.  Once I resolved that tomcat started.

The 2nd is that I found JWplayer on github (https://github.com/jwplayer/jwplayer) so maybe instead of not being able to script it according to the document that it could be "git clone" from there?

The 3rd is that in the last step where we run 'drush vset islandora_paged_content_djatoka_url "http://hostname/adore-djatoka/"' why isn't the hostname put into the properties file like the other variables?

The 4th is at the point I was installing Fedora it asked if I wanted to overwrite /usr/local/fedora or not.  If you chose the default, it exited and did nothing, had to re-run with 'Yes' to get it to work.

The 5th is it would have been nice to have the dependencies enabled - This of course could be optional but having the command to enable the modules via drush would have been nice.  At least my mouse hand wouldn't be numb after all of the clicking.   'drush en ... -y' in a script.

Otherwise 🥇 👍 

Now to convert this for RHEL/CentOS for use here.

**Comment by lutaylor** [comment]
Thank you for taking a look Brian! I will take a look at the issues you identified.

**Comment by bdgregg** [comment]
Luke, also shouldn't we be using the Islandora Video.js module instead of the JWplayer per the instructions on the islandora_jwplayer github README.md?

**Comment by lutaylor** [comment]
https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/pull/37

Here you go. 

I wasn't sure about what you meant by the missing dependancies? I think drush is enabling everything?

**Comment by bdgregg** [comment]
Dependencies = Drupal enabled modules - the modules were there, they just weren't all enabled.  It's been a bit so I'd have to run through it again to see exactly which weren't but if you enabled all of the ones installed then I think you're good.

**Comment by lutaylor** [comment]
I added just a -y to the drupal enables perhaps that will take care of what you were seeing? When the islandora modules enable with a -y it usually enables any drupal dependancies.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
