### ISSUE TITLE
Move meeting notes/minutes to Google Docs

### ISSUE THREAD

**Issue by highermath** [islandora-interest-groups/Islandora-DevOps-Interest-Group#39]
We seem to have a mixed history of getting meeting notes to a place where they can be found. Perhaps something more interactive, such as Google Docs, would better serve us.

**Comment by bryjbrown** [comment]
The strategy the IR interest group is starting to take is to use a Google Doc as a place to submit agenda items for the next upcoming meeting, and as a place to take notes during said meeting, and then archive that agenda + notes back to GH afterwards and clear the Google Doc to prep for the next meeting.

Kinda roundabout, but it saves people from having to fork and PR agenda submissions and notes. I'm comfortable with forking/PRing but it's still a PITA when all you wanna do is add one thing.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
