### ISSUE TITLE
[Stable] Redhat/Centos 6.6 Server Configuration

### ISSUE THREAD

**Issue by g7morris** [islandora-interest-groups/Islandora-DevOps-Interest-Group#5]
For those assigned to this issue by mention or Assignee: 

Please update this section https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/wiki/Software-Requirements-by-Distro  with the appropriate information for Red Hat 6.6 [Stable]

Attaching spreadsheets are fine. Please let me know if I've left anyone out or if you don't want this distro.

Assigned to: 
@bradspry
@pc37utn
@philred
@lo5an
@JacobSanford
@jpeak5
@mark-cooper
@lutaylor
@JacobSanford
@bradspry
@psuda1

**Comment by DonRichards** [comment]
Over a year old. Is this complete?

**Comment by pc37utn** [comment]
Is this supposed to be a list of which versions are needed to install Islandora, or which versions are commonly used?    It depends on how a server is maintained.  If you use the OS repo and stay up-to-date with it these versions change over time.   If you custom compile some of these programs, it depends on when and why you do that.
You could get rid of the versions and just have the OS version beside packages that are maintained with the OS and hten put the version numbers next to custom installs.

**Comment by g7morris** [comment]
Closing. Can reopen if group / individual decides to pursue topic.
