### ISSUE TITLE
[Stable] Ubuntu 14.04 LTS/Debian Server Configuration

### ISSUE THREAD

**Issue by g7morris** [islandora-interest-groups/Islandora-DevOps-Interest-Group#6]
For those assigned to this issue by mention or Assignee: 

Please update this section https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/wiki/Software-Requirements-by-Distro  with the appropriate information. 

Attaching spreadsheets are fine. Please let me know if I've left anyone out

Assigned to: 
@bradspry
@pc37utn
@philred
@lo5an
@JacobSanford
@jpeak5
@mark-cooper
@lutaylor
@JacobSanford
@bradspry
@psuda1

**Comment by lutaylor** [comment]
Have install documentation and got permission to release. Going to reformat and combine different sources. Should have this completed by next meeting.

**Comment by lutaylor** [comment]
Should get a fully working install up and running has a few areas that still need some TLC

Stock basic install doc from Discoverygarden:
https://docs.google.com/document/d/1nvbgvtduYbLaS6-vu_T3HOoCO1JROTY1CwtlIJ2Mi6A/edit?usp=sharing

Going to provide edit access to collaborators and once we think we got something we all like we can figure out best way to publish to community. 

This works with 14.04 it also should work with 12.04 with some minor tweaks e.g. apache conf in different location.

**Comment by g7morris** [comment]
Closing as I think @lutaylor covered this topic really well. https://github.com/islandora-interest-groups/Islandora-DevOps-Interest-Group/blob/master/Deployment%20Guides/Provisioning-Islandora-on-Ubuntu.md
